/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        card: 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        'card-border': 'hsl(var(--card-border))',
        popover: 'hsl(var(--popover))',
        'popover-foreground': 'hsl(var(--popover-foreground))',
        'popover-border': 'hsl(var(--popover-border))',
        primary: 'hsl(var(--primary))',
        'primary-foreground': 'hsl(var(--primary-foreground))',
        'primary-border': 'var(--primary-border)',
        secondary: 'hsl(var(--secondary))',
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        'secondary-border': 'var(--secondary-border)',
        muted: 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        'muted-border': 'var(--muted-border)',
        accent: 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        'accent-border': 'var(--accent-border)',
        destructive: 'hsl(var(--destructive))',
        'destructive-foreground': 'hsl(var(--destructive-foreground))',
        'destructive-border': 'var(--destructive-border)',
        gold: {
          50: '#FBF7EC',
          100: '#F6EFD3',
          200: '#ECDFA6',
          300: '#E0CB78',
          400: '#D4AF37',
          500: '#C49B2A',
          600: '#A67E22',
          700: '#7E5F1B',
          800: '#553F12',
          900: '#2C2009',
        },
        brown: {
          50: '#F8F5F0',
          100: '#EFE7DC',
          200: '#DCC8B2',
          300: '#C0A384',
          400: '#8A6A4A',
          500: '#5A3A22',
          600: '#4A2F1B',
          700: '#3A2615',
          800: '#2B1D17',
          900: '#1C130E',
        },
        cream: '#F8F5F0',
      },
      fontFamily: {
        sans: ['var(--app-font-sans)'],
        serif: ['var(--app-font-serif)'],
        mono: ['var(--app-font-mono)'],
        button: ['var(--app-font-button)'],
        heading: ['"Playfair Display"', 'serif'],
        body: ['Poppins', 'sans-serif'],
        btn: ['var(--app-font-button)'],
      },
      borderRadius: {
        sm: 'calc(var(--radius) - 4px)',
        md: 'calc(var(--radius) - 2px)',
        lg: 'var(--radius)',
        xl: 'calc(var(--radius) + 4px)',
      },
      maxWidth: {
        '8xl': '1440px',
      },
      boxShadow: {
        soft: '0 10px 40px -12px rgba(43, 29, 23, 0.18)',
        gold: '0 8px 30px -8px rgba(212, 175, 55, 0.45)',
        dark: '0 20px 60px -15px rgba(28, 19, 14, 0.55)',
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.6s ease-out forwards',
        shimmer: 'shimmer 2s linear infinite',
      },
    },
  },
  plugins: [],
};
